### ISSUE TITLE
Better documentation please

### ISSUE THREAD

**Issue by yefim** [tsuwatch/nazrin#16]
I'm having a hard time understanding what to pass into `.search` and `.query`. It would be great to document the `options` hash that `.search` takes in. If you flesh out some of the documentation, I would be more than willing to contribute some more in the same pattern!

**Comment by tsuwatch** [comment]
Thank you for the question.
`.search` can receive `ActiveRecord` methods and arguments. (ex: `{ method: :argument }`, for example, `{ eager_load: :foo }`, `{ joins: :foo }` etc.
`nazrin` just `#send` passed methods to the model.

nazrin uses `aws-sdk` inside.  `aws-sdk` requires `options[:query]`. `.query` is just passing arguments to this.
Details are written here. http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudSearchDomain/Client.html#search-instance_method

Okay, If you understand, I would like to write its contents.

**Comment by yefim** [comment]
@tsuwatch, awesome! Thanks for the quick reply :) I figured it out.
