### ISSUE TITLE
Multiple Models

### ISSUE THREAD

**Issue by t** [tsuwatch/nazrin#2]
Is this gem supporting multiple models? I guess the gem supports 1 model at the same time.
Do you have a plan for supporting multiple models?

**Comment by tsuwatch** [comment]
I'm sorry but I don'y have a plan for supporting multiple models.

**Comment by tsuwatch** [comment]
Do you mean you want to use two instances?

**Comment by t** [comment]
@tsuwatch 
Thank you for replying.

For example, I would like to implement search function to ``Product`` and ``Recipe`` models. But currently, the configuration can be wrote only 1 CloudSearch's endpoint, so I guess I can't use it for the 2 models at the same time. 
In this case, I need to choice ``Product`` or ``Recipe`` or create a model for search purpose.

I thought there are 2 ways for supporting to implement search function to multiple models.

(1) Supporting Multiple CloudSearch's domains(indexes)
Each model will have own CloudSearch's domain configuration. It looks regular way. of course, It requires extra money for increasing indexes.

(2) Supporting combined models' data by 1 domain(index)
Each model data will be sent to one CloudSearch's domain. It looks dirty way, but it will save the money.

Actually I need (2). I wonder I try to create a PR to explain details.

**Comment by tsuwatch** [comment]
Hmm...I see.
I will try to support (1).
But the other will wait for your PR.

**Comment by tsuwatch** [comment]
see #3
